class SessionSerializer
  # `confirmed_count` is passed in by a list, which counts the whole page in
  # one grouped query (SessionSerializer.confirmed_counts); asking each
  # session would be two COUNTs a row.
  def initialize(session, confirmed_count: nil)
    @session = session
    @confirmed_count = confirmed_count
  end

  def self.confirmed_counts(sessions)
    Booking.confirmed.where(session_id: sessions.map(&:id)).group(:session_id).count
  end

  def as_json(*)
    {
      id: session.id,
      activity_id: session.activity_id,
      activity_name: session.activity.name,
      activity_emoji: session.activity.emoji,
      company_id: session.company_id,
      company_name: session.company.name,
      coach_id: session.coach_id,
      coach_name: session.coach&.full_name,
      # The room or cabin, for a gym that runs them (FEATURES[:spaces]).
      space_id: session.space_id,
      space_name: session.space&.name,
      # A one-to-one slot reads as an appointment (free / taken), not a class.
      individual: session.activity.individual?,
      # Set when the session was generated by a weekly class, so the
      # calendar can offer to stop the series from any one of its sessions.
      recurring_schedule_id: session.recurring_schedule_id,
      starts_at: session.starts_at,
      ends_at: session.ends_at,
      capacity: session.capacity,
      confirmed_count: confirmed_count,
      price: session.price,
      status: session.status,
      availability: availability
    }
  end

  private

  attr_reader :session

  def confirmed_count
    @confirmed_count ||= session.confirmed_bookings_count
  end

  # Held seats are confirmed ones (Booking::HELD_STATUSES), so the count
  # above is also what fullness is measured against.
  def availability
    return "cancelled" if session.cancelled?
    return "full" if confirmed_count >= session.capacity

    "available"
  end
end
